### ISSUE TITLE
TypeError: questFetcher.fetchQuestInventory(...).then is not a function

### ISSUE THREAD

**Issue by pandapaul** [pandapaul/minecraft-dailies-server#9]
```
2016-09-19T15:26:05.179190+00:00 heroku[router]: at=info method=GET path="/ZombieB*******/quests" host=www.minecraftdailies.com request_id=ddc1851b-8b61-49ea-a5ca-cbfe920797fd fwd="" dyno=web.1 connect=3ms service=27ms status=500 bytes=250
2016-09-19T15:26:05.212257+00:00 app[web.1]: TypeError: questFetcher.fetchQuestInventory(...).then is not a function
2016-09-19T15:26:05.212271+00:00 app[web.1]:     at /app/routes/quests.js:19:14
2016-09-19T15:26:05.212274+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-09-19T15:26:05.212275+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:131:13)
2016-09-19T15:26:05.212276+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2016-09-19T15:26:05.212276+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-09-19T15:26:05.212277+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:277:22
2016-09-19T15:26:05.212278+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2016-09-19T15:26:05.212279+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)
2016-09-19T15:26:05.212279+00:00 app[web.1]:     at Function.handle (/app/node_modules/express/lib/router/index.js:176:3)
2016-09-19T15:26:05.212280+00:00 app[web.1]:     at router (/app/node_modules/express/lib/router/index.js:46:12)
2016-09-19T15:26:05.212281+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2016-09-19T15:26:05.212281+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
2016-09-19T15:26:05.212282+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:280:7
2016-09-19T15:26:05.212283+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2016-09-19T15:26:05.212283+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:271:10)
2016-09-19T15:26:05.212284+00:00 app[web.1]:     at SendStream.error (/app/node_modules/serve-static/index.js:120:7)

```

**Comment by pandapaul** [comment]
Resolved with commit 11d83f828ca64f4ad95bb2d702df9cbe940c4f12
